### ISSUE TITLE
Bug: IL2CPP Build Failing

### ISSUE THREAD

**Issue by Bryan-Legend** [jilleJr/Newtonsoft.Json-for-Unity.Converters#34]
## Actual behavior
When making a IL2CPP  build I'm getting the following errors.

IL2CPP error for method 'UnityEngine.ColliderDistance2D Newtonsoft.Json.UnityConverters.Physics2D.ColliderDistance2DConverter::CreateInstanceFromValues(Newtonsoft.Json.UnityConverters.ValuesArray`1<System.Object>)' in ColliderDistance2DConverter.cs:21
Additional information: Stack empty.

It also happens for CullingGroupEventConverter and RandomStateConverter.

I didn't need these classes so I just commented them out as a good workaround. I'm just reporting this bug for your knowledge and don't personally need a fix.

## Steps to reproduce

- New project
- Import `jillejr.newtonsoft.json-for-unity` via UPM
- Import `jillejr.newtonsoft.json-for-unity.converters` via UPM
- Try to make an IL2CPP build.

## Details

Host machine OS running Unity Editor 👉 Windows

Unity build target 👉 Nintendo Switch

Newtonsoft.Json-for-Unity package version 👉 12.0.301

Newtonsoft.Json-for-Unity.Converters package version 👉 1.0.0

I was using Unity version 👉 2019.3.7f1

## Checklist

- [x] Shutdown Unity, deleted the /Library folder, opened project again in Unity, and problem still remains.
- [x] Checked to be using latest version of the package.

**Comment by jilleJr** [comment]
Hey! That's a very kind bug report :) 

Thanks for reporting it ❤️
Will investigate when I'm done with some of the other issues from the main repo jilleJr/Newtonsoft.Json-for-Unity

**Comment by jilleJr** [comment]
The common denominator is my weird usage of `__makeref`. Will probably have to downgrade to boxing the structs instead. Can probably get a fix of this in to v1.1.0 soon™

**Comment by jilleJr** [comment]
The common denominator is my weird usage of `__makeref`. Will probably have to downgrade to boxing the structs instead. Can probably get a fix of this in to v1.1.0 soon™
