### ISSUE TITLE
ScriptableObjects List support

### ISSUE THREAD

**Issue by dburongarcia** [jilleJr/Newtonsoft.Json-for-Unity.Converters#38]
Hello, I saw the solution from @sindrijo but after installing the converters I still get the error  "Data must be instantiated using the ScriptableObject.CreateInstance method instead of new Data". Are ScriptableObjects supported and how to de/serialize them?

What I'm trying to do is to de/serialize a ScriptableObject with a List of ScriptableObjects inside. When I serialize it works, but deserializing I get that error. 

https://github.com/jilleJr/Newtonsoft.Json-for-Unity/issues/28#issuecomment-579997306 

> Here is an update version which supports ScriptableObjects.
> 
> ```cs
> using System;
> using System.Collections.Generic;
> using Newtonsoft.Json;
> using Newtonsoft.Json.Converters;
> using Newtonsoft.Json.Linq;
> using UnityEngine;
> 
> internal static class UnityTypeSupport
> {
>     
> #if UNITY_EDITOR
>     [UnityEditor.InitializeOnLoadMethod]
> #else
>     [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
> #endif
>     private static void Init()
>     {
>         JsonConvert.DefaultSettings += GetJsonSerializerSettings;
>     }
> 
>     private static JsonSerializerSettings GetJsonSerializerSettings()
>     {
>         var settings = new JsonSerializerSettings();
>         settings.Converters.Add(new UnityTypeConverter());
>         settings.Converters.Add(new ScriptableObjectCreator());
>         return settings;
>     }
> 
>     private class UnityTypeConverter : JsonConverter
>     {
>         private static readonly HashSet<Type> UnityEngineTypes;
>         
>         static UnityTypeConverter()
>         {
>             UnityEngineTypes = new HashSet<Type>(typeof(UnityEngine.Object).Assembly.GetTypes());
>         }
>         
>         public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
>         {
>             writer.WriteRawValue(JsonUtility.ToJson(value));
>         }
> 
>         public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
>         {
>             if (typeof(ScriptableObject).IsAssignableFrom(objectType))
>             {
>                 JsonUtility.FromJsonOverwrite(JObject.Load(reader).ToString(), existingValue);
>                 return existingValue;
>             }
>             
>             return JsonUtility.FromJson(JObject.Load(reader).ToString(), objectType);
>         }
> 
>         public override bool CanConvert(Type objectType)
>         {
>             return IsUnityEngineType(objectType);
>         }
> 
>         private static bool IsUnityEngineType(Type objectType)
>         {
>             return UnityEngineTypes.Contains(objectType);
>         }
>     }
>     
>     private class ScriptableObjectCreator : CustomCreationConverter<ScriptableObject>
>     {
>         public override ScriptableObject Create(Type objectType)
>         {
>             return ScriptableObject.CreateInstance(objectType);
>         }
>     }
> }
> ```

**Comment by jilleJr** [comment]
This feature will later be available from v1.1.0 and is already available from the v1.1.0-preview.1 version.
@dburongarcia Please check it out and see if the solution is enough.

The issue is tested with the following code and shown to be working:
https://github.com/jilleJr/Newtonsoft.Json-for-Unity.Converters/blob/a55220fc48d682f6d8cbdda37a658f7553356f9f/Assets/Newtonsoft.Json.UnityConverters.Tests/Issues/Issue38.cs#L7-L72
