### ISSUE TITLE
Help: PopulateObject support?

### ISSUE THREAD

**Issue by nialna** [jilleJr/Newtonsoft.Json-for-Unity.Converters#42]
## Expected behavior

I have tried using PopulateObject to override data on a scriptable object based on a json, but the data doesn't see to actually change when deserializing.

## Actual behavior

The PopulateObject call doesn't fail, but nothing is changed in the object. Just wanted to ask if it is actually expected to work or if it's missing as this library is new?

**Comment by jilleJr** [comment]
Hi @nialna !

This is actually on my to-do list (quite high as well) and can already be found in #20. It is not available in v1.0 but I'm aiming it to be available in v1.1.

I'm currently very busy with obtaining drivers license, so sorry to say that all my focus will go there for about a month. Expect some delay before this feature is added.

I'm closing this as duplicate in favor of #20
