### ISSUE TITLE
[Feature Request] Serialize/Deserialize AssetReference from Addressables

### ISSUE THREAD

**Issue by maskedmouse** [jilleJr/Newtonsoft.Json-for-Unity.Converters#66]
Would it be possible to add [AssetReference](https://docs.unity3d.com/Packages/com.unity.addressables@1.19/api/UnityEngine.AddressableAssets.AssetReference.html) from the [Addressables package](https://docs.unity3d.com/Packages/com.unity.addressables@1.19/manual/index.html)?
If you have a Scriptable Object with an AssetReference field it currently cannot be serialized due to all the other properties unity has tied to them.

```Exception: Attempting to use an invalid operation handle
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle.get_InternalOp () (at Library/PackageCache/com.unity.addressables@1.19.17/Runtime/ResourceManager/AsyncOperations/AsyncOperationHandle.cs:454)
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle.get_OperationException () (at Library/PackageCache/com.unity.addressables@1.19.17/Runtime/ResourceManager/AsyncOperations/AsyncOperationHandle.cs:480)

**Comment by jilleJr** [comment]
Hello @maskedmouse!

I've deliberately skipped any asset serialization, with the exception of serializableobject, as they usually contains tricky and unportable values that change between executions, builds, or where they're hosted, making serialization pointless as the data cannot be consistently deserialized anymore without data loss or other unwanted side effects.

Could you provide a more concrete example of what you wish support for?

1. Where do you want to serialize? Ex when saving the game or to transfer data over some medium (internet, USB, whatev)?
2. Where do you want to deserialize? Ex loading a save file or receiving data over some medium?
3. What kind of assets do you wish supported? Images? Plain texts? Other scriptableobjects?

Alternatively, do you think the serialization should try to ignore those fields instead? If so then you should be able to apply the [`[JsonIgnore]` attribute](https://www.newtonsoft.com/json/help/html/PropertyJsonIgnore.htm)

**Comment by maskedmouse** [comment]
The AssetReference has an AssetGUID property. Since asset GUIDs are usually persistent throughout the project they can be used to recreate the AssetReference.
Once you pass the recreated AssetReference to the Addressables API, it'll figure out what asset it was and load it for you.

The AssetReference has a constructor that takes the asset GUID as parameter.
`AssetReference assetRef = new AssetReference(guid);` < - > `AssetReference.AssetGUID`

**Where do you want to serialize? Ex when saving the game or to transfer data over some medium (internet, USB, whatev)?**
Saving a game or part of its data. Like an Item having an AssetReference to a sprite asset.
Loading this data from json and giving it to an inventory UI, it can use the AssetReference to load the sprite icon and unload when it is not needed anymore. Same goes for GameObject prefab references. You can just give the AssetReference to the Addressables API and load in the actual GameObjects. All it requires is a GUID converted to an AssetReference.

**Where do you want to deserialize? Ex loading a save file or receiving data over some medium?**
Runtime loading in a save file (json).

**What kind of assets do you wish supported? Images? Plain texts? Other scriptableobjects?**
The AssetReference is a class with an AssetGUID property. With that AssetReference you can load in whatever you want.
When serializing to Json convert AssetReference into a string GUID
When deserializing from Json convert the GUID back into an AssetReference

```
public class Item
{
	public int ID;
	public string Description;
	public AssetReference IconReference;
}
```

```
{
	"ID" : 0,
	"Description" : "",
	"IconReference" : "923f4b9871187124094e2c7f30d7925a"
}
```

**Comment by jilleJr** [comment]
Thanks for the elaborate response!

I'll look into it, but I'm also questioning the use case. I do not think it's wise to store for example an item sprite in the save file. Instead the item should have a pretty much hardcoded sprite that it uses.

It's a good idea to have a separate data structure just for storing the data than the class types you're using in the actual game. The separation of concerns for the data structures give better flexibility for deciding what data is actually stored and what is not so that not excess data that needn't be stored is, as well as leads to better maintainability as there's no risk of changing the structure of the data store format when changing the structure of the runtime objects.

I advice against using this procedure for your project, however I can see value in supporting AssetReference in other scenarios.

**Comment by jilleJr** [comment]
Happy to announce that AssetReference is now supported, starting with v1.4.0: https://github.com/jilleJr/Newtonsoft.Json-for-Unity.Converters/releases/tag/1.4.0

The package is already available on Cloudsmith (https://cloudsmith.io/~jillejr/repos/newtonsoft-json-for-unity/packages/detail/npm/jillejr.newtonsoft.json-for-unity.converters/1.4.0/) and will become available on OpenUPM as soon as their build pipelines notices the release (https://openupm.com/packages/jillejr.newtonsoft.json-for-unity.converters/?subPage=pipelines)
