### ISSUE TITLE
Bug: It breaks Addressables and Cloud Content Delivery

### ISSUE THREAD

**Issue by israelillan** [jilleJr/Newtonsoft.Json-for-Unity.Converters#93]
## Expected behavior

It won't affect Addressables+CCD

## Actual behavior

If you have a project that uses Addressables hosted in unity's cloud content delivery system it fails when uploading the addressables

## Steps to reproduce

- New project
- Import `jillejr.newtonsoft.json-for-unity` via UPM
- Import `jillejr.newtonsoft.json-for-unity.converters` via UPM
- Add Addressables package (com.unity.addressables 1.21.19)
- Add CCD management package (com.unity.services.ccd.management 2.1.0)
- Configure an addressable antd try to upload it to CCD (https://docs.unity.com/ugs/manual/ccd/manual/UnityCCDWalkthrough)
- You should be getting "NotImplementedException" in Unity.Services.Ccd.Management.Http.JsonObjectConverter CanConvert

## Details

Host machine OS running Unity Editor 👉 Mac OS running unity editor 2022.3.10f1

Unity build target 👉 Android

Newtonsoft.Json-for-Unity package version 👉 3.2.1

Newtonsoft.Json-for-Unity.Converters package version 👉 1.6.3

I was using Unity version 👉 2022.3.10f1

## Checklist

- [x] Shutdown Unity, deleted the /Library folder, opened project again in Unity, and problem still remains.
- [x] Checked to be using latest version of the package.

**Comment by applejag** [comment]
Hello @israelillan, thanks for reporting this!

It sounds like this package is just finding some converters in the CCD package and then adding them.

Could you try adding a [config file](https://github.com/applejag/Newtonsoft.Json-for-Unity.Converters?tab=readme-ov-file#custom-settings-through-config-file) and configure it to not use the CCD converters?

**Comment by israelillan** [comment]
That seems do the trick, thanks!

**Comment by applejag** [comment]
Nice!

I apologize for the odd defaults here of using all converters it can find. It made sense at one point I'm sure.

But now I can't change it as that would cause breaking changes.

---

Closing this as resolved
