### ISSUE TITLE
Help: Self referencing loop detected when deployed to HoloLens 2

### ISSUE THREAD

**Issue by Horstexplorer** [jilleJr/Newtonsoft.Json-for-Unity.Converters#95]
## Expected behavior

When attempting to build and deploy a Unity project targeting the Universal Windows Platform using the IL2CPP scripting backend, the converters should ensure that Unity classes, such as Vector3, can be properly serialized and deserialized. 

## Actual behavior

When attempting to build and deploy a Unity project targeting the Universal Windows Platform using the IL2CPP scripting backend, the serialization and deserialization of Unity classes such as Vector3 will fail with an error such as
``JsonSerializationException: Self referencing loop detected for property 'normalized' with type 'UnityEngine.Vector3'``

## Steps to reproduce

- New project with MRTK3
- Import `com.unity.nuget.newtonsoft-json` via UPM
- Import `jillejr.newtonsoft.json-for-unity.converters` via UPM
- Add following script to scene:

```csharp
void Update() {
   var json = JsonConvert.SerializeObject(Vector3.zero);
}
```

- Add following content to link.xml

```xml
<linker>
  <assembly fullname="Newtonsoft.Json">
    <type fullname="*" preserve="all"/>
  </assembly>
  <assembly fullname="Newtonsoft.Json.Converters">
    <type fullname="*" preserve="all"/>
  </assembly>
  <assembly fullname="Newtonsoft.Json.UnityConverters">
    <type fullname="*" preserve="all"/>
  </assembly>
</linker>
```

- Deploy and run the game

## Details

Windows 11
UWP (IL2CPP) > D3D for ARM64 > HoloLens 2

Newtonsoft.Json 3.2.1
Newtonsoft.Json-for-Unity.Converters 1.6.3
Unity version 2022.3.21f1

## Checklist
- [x] Shutdown Unity, deleted the /Library folder, opened project again in Unity, and problem still remains.
- [x] Checked to be using latest version of the package.

## Additional

I have tried manually configuring the link.xml to preserve the assemblies as has been recommended in different issues.

**Comment by applejag** [comment]
Hello @Horstexplorer, thanks for reporting this!

This sounds very related to code stripping.

In the "additional" info section, you mentioned you tried using `link.xml`. Did that help?

**Comment by Horstexplorer** [comment]
Thank you for your response!
Adding the link.xml file didn't initially affect the build. I had to manually clear the build output and perform a complete rebuild, which seems to have resolved the issue.
